config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :attendees, controllers: { passwords: 'devise/attendees/passwords' }
  devise_for :users

  resources :events do
    post 'upload_attendees', on: :member
    post 'publish', on: :member
    post 'unpublish', on: :member
    resources :attendees
  end

  resources :contents
  resources :clients
  resources :tokens do
    post 'attach_content_hotspot', on: :collection
    post 'attach_url_hotspot', on: :collection
  end

  resources :hotspots, only: %i[create destroy]
  resources :labels do
    patch :update_text, on: :collection
  end

  root 'events#index'

  admin_web_constraint = lambda do |request|
    current_user = request.env['warden'].user(:user)
    current_user.present? && current_user.respond_to?(:has_role?) && current_user.has_role?(:superadmin)
  end

  constraints admin_web_constraint do
    mount Flipflop::Engine => '/flipflop'
  end
end

app/models/content.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: contents
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Content < ApplicationRecord
  ALLOWED_MIME_TYPES = %w[
    application/pdf
    image/jpeg
    image/png
    image/webp
    video/mp4
    image/gif
    image/gif
    application/vnd.ms-powerpoint
    application/vnd.openxmlformats-officedocument.presentationml.presentation
  ].freeze

  acts_as_taggable_on :tags

  has_many :hotspots, dependent: :destroy
  has_one_attached :file

  validates :name, presence: true
  validate :acceptable_file

  delegate :key, to: :file, allow_nil: false, prefix: true

  scope :images, -> { joins(:file_attachment, :file_blob).where("content_type LIKE 'image/%'") }

  def self.mime_types
    ALLOWED_MIME_TYPES.join(', ')
  end

  def acceptable_file
    return unless file.attached?

    document_types = [
      'application/vnd.ms-powerpoint',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation'
    ]

    max_file_size = if document_types.include?(file.content_type)
                      # only document types
                      25.megabyte
                    else
                      50.megabyte
                    end

    errors.add(:file, 'is too big') if file.byte_size >= max_file_size
  end
end

app/controllers/contents_controller.rb
# frozen_string_literal: true

class ContentsController < ApplicationController
  before_action :set_content, only: %i[show edit update destroy]

  # GET /contents or /contents.json
  def index
    @search = Content.includes(:tags, file_attachment: :blob).reverse_chronologically
    @search = @search.images if params[:type] == 'images'
    @search = @search.ransack(params[:q])

    authorize @search.result

    respond_to do |format|
      format.html { @contents = set_page_and_extract_portion_from @search.result }
      format.csv { render csv: @search.result }
      format.json { render json: @search.result.limit(20).as_json(include: :file_blob) }
    end
  end

  # GET /contents/1 or /contents/1.json
  def show; end

  # GET /contents/new
  def new
    @content = Content.new
    authorize @content
  end

  # GET /contents/1/edit
  def edit
    authorize @content
  end

  # POST /contents or /contents.json
  def create
    authorize(@content = Content.new(content_params))

    if @content.save
      flash[:notice] = 'Content was successfully created.'
    else
      flash[:alert] = @content.errors.full_messages.join('. ')
    end

    respond_to do |format|
      format.html do
        redirect_to contents_url
      end
    end
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    authorize @content

    if @content.update(content_params)
      flash[:notice] = 'Content was successfully updated.'
    else
      flash[:alert] = @content.errors.full_messages.to_sentence
    end

    respond_to do |format|
      format.html { redirect_to contents_url }
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    authorize @content

    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_content
    @content = Content.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def content_params
    params.require(:content).permit(:name, :file, :tag_list)
  end
end

app/helpers/contents_helper.rb
# frozen_string_literal: true

module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_with(model: content, data: { controller: 'validation' }) do |form| %>
  <div class="row">
    <div class="form-group col-5">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <% if params[:action] == 'new' %>
      <div class="form-group col-5">
        <%= form.label :file, 'Choose File' %>
        <%= form.file_field :file, label: 'Report', class: 'form-control', accept: Content.mime_types, direct_upload: true, data: { controller: 'direct-uploader' } %>
        <small class="form-text text-muted"></small>
      </div>
    <% else %>
      <div class="form-group col-5">
        <%= form.label :file, 'File' %>
        <input type='text' class='form-control' disabled='true' value='<%= content.file.filename %>'>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="form-group col-10">
      <%= form.label :tag_list %>
      <%= form.text_field :tag_list, class: 'form-control', value: content.tag_list.join(',') %>
    </div>
  </div>

  <div class="card-footer pl-0">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Contents</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item"><%= link_to 'Contents', contents_path %></div>
      <div class="breadcrumb-item">Editing Content</div>
    </div>
  </div>
  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>Editing Content</h4>
      </div>
      <div class="card-body">
        <%= render 'form', content: @content %>
      </div>
    </div>
  </div>
</section>

<%= link_to icon('fas fa-arrow-left', 'Back'), contents_path, class: 'btn btn-icon icon-left btn-secondary d-mobile-none' %>

<% content_for(:page_title, 'Editing Content') %>

app/views/contents/index.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Content Library</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item">List of Contents</div>
    </div>
  </div>

  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>List of Contents</h4>
        <div class="card-header-action">
          <%= link_to icon('fas fa-plus', 'New Content'), new_content_path, class: 'btn btn-icon icon-left btn-primary' %>
          <%= render 'shared/card_dropdown' do %>
            <%= link_to icon('fas fa-download', 'Export Data'), contents_path(format: :csv, q: request.params[:q]), class: 'dropdown-item has-icon' %>
            <%= link_to icon('fas fa-print', 'Print Page'), 'javascript:window.print()', class: 'dropdown-item has-icon' %>
          <% end %>
        </div>
      </div>
      <div class="card-body" data-controller="infinite-page">
        <!--
        <#= search_form_for @search, remote: true, data: { controller: 'turbolinks-form' }, html: { class: 'form-row' } do |f| #>
          <div class="form-group col-sm-10">
            <#= f.text_field :name_cont, class: 'form-control m-input m-input--solid', placeholder: 'Name' #>
          </div>
          <div class="form-group col-sm-2 text-right">
            <#= f.button icon('fas fa-search', 'Search'), name: nil, class: 'btn btn-icon icon-left btn-primary' #>
          </div>
        <# end #>
        -->
        <div class="table-responsive">
          <table class="table table-striped table-md">
            <thead>
              <tr>
                <th>Name</th>
                <th>Tags</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody data-target="infinite-page.container">
              <% @contents.each do |content| %>
                <tr data-target="infinite-page.item">
                  <td><%= content.name %></td>
                  <td>
                    <% content.tags.each do |tag| %>
                      <span class='badge badge-light'>
                        <%= tag %>
                      </span>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to icon('fas fa-link'), url_for(content.file), title: 'Download file', class: 'btn btn-icon btn-sm btn-info mr-1', target: '_blank' %>
                    <%= link_to icon('fas fa-edit'), edit_content_path(content), title: 'Edit it', class: 'btn btn-icon btn-sm btn-warning mr-1' %>
                    <%= link_to icon('fas fa-trash'), content, title: 'Destroy it', class: 'btn btn-icon btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?', remote: true } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= link_to 'Next page', contents_path(page: @page.next_number, q: request.params[:q]), data: { target: 'infinite-page.more' } unless @page.last? %>
        </div>
      </div>
    </div>
  </div>
</section>

<% content_for(:page_title, 'List of Contents') %>

app/views/contents/new.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Contents</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item"><%= link_to 'Contents', contents_path %></div>
      <div class="breadcrumb-item">New Content</div>
    </div>
  </div>
  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>New Content</h4>
      </div>
      <div class="card-body">
        <%= render 'form', content: @content %>
      </div>
    </div>
  </div>
</section>

<%= link_to icon('fas fa-arrow-left', 'Back'), contents_path, class: 'btn btn-icon icon-left btn-secondary d-mobile-none' %>

<% content_for(:page_title, 'New Content') %>

app/views/contents/show.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Contents</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item"><%= link_to 'Contents', contents_path %></div>
      <div class="breadcrumb-item">Show Content</div>
    </div>
  </div>

  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>Show Content</h4>
      </div>
      <div class="card-body">
        <dl class="row">
        </dl>
      </div>
    </div>
  </div>
</section>

<%= link_to icon('fas fa-edit', 'Edit'), edit_content_path(@content), class: 'btn btn btn-icon icon-left btn-warning' %>
<%= link_to icon('fas fa-arrow-left', 'Back'), contents_path, class: 'btn btn-icon icon-left btn-secondary d-mobile-none' %>

<% content_for(:page_title, 'Show Content') %>