config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :attendees, controllers: { passwords: 'devise/attendees/passwords' }
  devise_for :users

  resources :events do
    post 'upload_attendees', on: :member
    post 'publish', on: :member
    post 'unpublish', on: :member
    resources :attendees
  end

  resources :contents
  resources :clients
  resources :tokens do
    post 'attach_content_hotspot', on: :collection
    post 'attach_url_hotspot', on: :collection
  end

  resources :hotspots, only: %i[create destroy]
  resources :labels do
    patch :update_text, on: :collection
  end

  root 'events#index'

  admin_web_constraint = lambda do |request|
    current_user = request.env['warden'].user(:user)
    current_user.present? && current_user.respond_to?(:has_role?) && current_user.has_role?(:superadmin)
  end

  constraints admin_web_constraint do
    mount Flipflop::Engine => '/flipflop'
  end
end

app/views/shared/_alert_validation.html.erb
<!-- USE THIS PARTIAL INSIDE FORM IF YOU WANT TO USE SERVER SIDE VALIDATION -->
<% if resource.errors.present? %>
  <div class="alert alert-danger alert-dismissible show fade">
    <div class="alert-body">
      <button class="close" data-dismiss="alert"><span>&times;</span></button>
      <h5>Please correct the following items and try again:</h5>
      <ul class="pl-3">
        <% resource.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_card_dropdown.html.erb
<div class="dropdown">
  <a href="#" data-toggle="dropdown" class="btn btn-icon btn-secondary"><i class="fas fa-ellipsis-h"></i></a>
  <div class="dropdown-menu dropdown-menu-right">
    <%= yield %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="main-footer">
  <div class="footer-left">
    EVE Manager
  </div>
  <div class="footer-right">
    2021
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg main-navbar">
  <form class="form-inline mr-auto">
    <ul class="navbar-nav mr-3">
      <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
    </ul>
  </form>
  <ul class="navbar-nav navbar-right">

    <li class="dropdown">
      <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
        <%= image_tag('avatar/avatar-1.png', class: 'rounded-circle mr-1') %>
        <div class="d-sm-none d-lg-inline-block">
          <%= current_user.first_name %>
        </div>
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <%= link_to destroy_user_session_path, :method => :delete, class: "dropdown-item has-icon text-danger" do %>
          <i class="fas fa-sign-out-alt"></i> Logout
        <% end %>
      </div>
    </li>
  </ul>
</nav>

app/views/shared/_sidebar.html.erb
<div class="main-sidebar sidebar-style-2">
  <aside id="sidebar-wrapper">
    <ul class="sidebar-menu" data-controller="sidebar">
      <% if current_user.superadmin? %>
        <li class="menu-header">Admin</li>
        <li>
          <%= link_to admin_root_path, class: "nav-link" do %>
            <i class="fas fa-tools"></i> <span>Admin</span>
          <% end %>
        </li>
      <% end %>

      <li class="menu-header">Manage</li>

      <li class='<%= active_nav_item('clients') %>'>
        <%= link_to clients_path, class: 'nav-link' do %>
        <i class='fas fa-user-tie'></i><span>Clients</span>
        <% end %>
      </li>

      <li class='<%= active_nav_item('events') %>'>
        <%= link_to events_path, class: 'nav-link' do %>
        <i class='fas fa-mountain'></i><span>Events</span>
        <% end %>
      </li>

      <li class='<%= active_nav_item('contents') %>'>
        <%= link_to contents_path, class: 'nav-link' do %>
        <i class='fas fa-truck-moving'></i><span>Content Library</span>
        <% end %>
      </li>

      <%#= render 'shared/sidebar_dropdown', title: 'Resources', icon: 'fas fa-file-alt' do %>
      <!--
        <li class="<#= active_nav_item('customers', crud_actions) #>">
          <#= link_to 'Customers', customers_path, class: 'nav-link' #>
        </li>
      -->
      <%# end %>
    </ul>
  </aside>
</div>

app/views/shared/_sidebar_dropdown.html.erb
<li class="nav-item dropdown">
  <a href="#" class="nav-link has-dropdown" data-toggle="dropdown">
    <i class="<%= icon %>"></i> <span><%= title %></span>
  </a>
  <ul class="dropdown-menu">
    <%= yield %>
  </ul>
</li>

app/views/shared/_toastr.html.erb
<% flash.each do |type, msg| %>
  <% if msg.present? && msg.is_a?(String) %>
    <div data-controller="toastr" data-toastr-type="<%= type %>" data-toastr-message="<%= msg %>"></div>
  <% end %>
<% end %>