config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :attendees, controllers: { passwords: 'devise/attendees/passwords' }
  devise_for :users

  resources :events do
    post 'upload_attendees', on: :member
    post 'publish', on: :member
    post 'unpublish', on: :member
    resources :attendees
  end

  resources :contents
  resources :clients
  resources :tokens do
    post 'attach_content_hotspot', on: :collection
    post 'attach_url_hotspot', on: :collection
  end

  resources :hotspots, only: %i[create destroy]
  resources :labels do
    patch :update_text, on: :collection
  end

  root 'events#index'

  admin_web_constraint = lambda do |request|
    current_user = request.env['warden'].user(:user)
    current_user.present? && current_user.respond_to?(:has_role?) && current_user.has_role?(:superadmin)
  end

  constraints admin_web_constraint do
    mount Flipflop::Engine => '/flipflop'
  end
end

app/models/client.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: clients
#
#  id         :bigint           not null, primary key
#  name       :string           default(""), not null
#  slug       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_clients_on_name  (name) UNIQUE
#  index_clients_on_slug  (slug) UNIQUE
#
class Client < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :events

  validates :name, presence: true, uniqueness: true
end

app/controllers/clients_controller.rb
# frozen_string_literal: true

class ClientsController < ApplicationController
  before_action :set_client, only: %i[show edit update destroy]

  # GET /clients or /clients.json
  def index
    @search = Client.reverse_chronologically.ransack(params[:q])
    @clients = set_page_and_extract_portion_from @search.result

    authorize @clients

    respond_to do |format|
      format.any(:html, :json) {}
      format.csv { render csv: @search.result }
    end
  end

  # GET /clients/1 or /clients/1.json
  def show; end

  # GET /clients/new
  def new
    @client = Client.new
    authorize @client
  end

  # GET /clients/1/edit
  def edit; end

  # POST /clients or /clients.json
  def create
    @client = Client.new(compact_parameters)
    authorize @client

    if @client.save
      flash[:notice] = 'Client was successfully created.'
    else
      flash[:alert] = @client.errors.full_messages.to_sentence
    end

    respond_to do |format|
      format.html { redirect_to clients_url }
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    if @client.update(compact_parameters)
      flash[:notice] = 'Client was successfully updated.'
    else
      flash[:alert] = @client.errors.full_messages.to_sentence
    end

    respond_to do |format|
      format.html { redirect_to edit_client_url(@client) }
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.friendly.find(params[:id])
    authorize @client
  end

  # Only allow a list of trusted parameters through.
  def client_params
    params.require(:client).permit(:name, :slug)
  end

  def compact_parameters
    client_params[:slug].present? ? client_params : { name: client_params[:name] }
  end
end

app/helpers/clients_helper.rb
# frozen_string_literal: true

module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, data: { controller: 'validation' }) do |form| %>
  <div class="row">
    <div class="col-5 form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control', autofocus: true %>
    </div>

    <div class="col-5 form-group">
      <%= form.label :slug %>
      <%= form.text_field :slug, class: 'form-control', autofocus: true %>
    </div>
  </div>
  <div class="card-footer pl-0">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Clients</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item"><%= link_to 'Clients', clients_path %></div>
      <div class="breadcrumb-item">Editing Client</div>
    </div>
  </div>
  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>Editing Client</h4>
      </div>
      <div class="card-body">
        <%= render 'form', client: @client %>
      </div>
    </div>
  </div>
</section>

<%= link_to icon('fas fa-eye', 'Show'), @client, class: 'btn btn-icon icon-left btn-info' %>
<%= link_to icon('fas fa-arrow-left', 'Back'), clients_path, class: 'btn btn-icon icon-left btn-secondary d-mobile-none' %>

<% content_for(:page_title, 'Editing Client') %>

app/views/clients/index.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Clients</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item">List of Clients</div>
    </div>
  </div>

  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>List of Clients</h4>
        <div class="card-header-action">
          <%= link_to icon('fas fa-plus', 'New Client'), new_client_path, class: 'btn btn-icon icon-left btn-primary' %>
          <%= render 'shared/card_dropdown' do %>
            <%= link_to icon('fas fa-download', 'Export Data'), clients_path(format: :csv, q: request.params[:q]), class: 'dropdown-item has-icon' %>
            <%= link_to icon('fas fa-print', 'Print Page'), 'javascript:window.print()', class: 'dropdown-item has-icon' %>
          <% end %>
        </div>
      </div>
      <div class="card-body" data-controller="infinite-page">
        <!--
        <#= search_form_for @search, remote: true, data: { controller: 'turbolinks-form' }, html: { class: 'form-row' } do |f| #>
          <div class="form-group col-sm-10">
            <#= f.text_field :name_cont, class: 'form-control m-input m-input--solid', placeholder: 'Name' #>
          </div>
          <div class="form-group col-sm-2 text-right">
            <#= f.button icon('fas fa-search', 'Search'), name: nil, class: 'btn btn-icon icon-left btn-primary' #>
          </div>
        <# end #>
        -->
        <div class="table-responsive">
          <table class="table table-striped table-md">
            <thead>
              <tr>
                <th>Name</th>
                <th>Slug</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody data-target="infinite-page.container">
              <% @clients.each do |client| %>
                <tr data-target="infinite-page.item">
                  <td><%= client.name %></td>
                  <td><%= client.slug %></td>
                  <td>
                    <%= link_to icon('fas fa-eye'), client, title: 'Show it', class: 'btn btn-icon btn-sm btn-info mr-1' %>
                    <%= link_to icon('fas fa-edit'), edit_client_path(client), title: 'Edit it', class: 'btn btn-icon btn-sm btn-warning mr-1' %>
                    <%= link_to icon('fas fa-trash'), client, title: 'Destroy it', class: 'btn btn-icon btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?', remote: true } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= link_to 'Next page', clients_path(page: @page.next_number, q: request.params[:q]), data: { target: 'infinite-page.more' } unless @page.last? %>
        </div>
      </div>
    </div>
  </div>
</section>

<% content_for(:page_title, 'List of Clients') %>

app/views/clients/new.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Clients</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item"><%= link_to 'Clients', clients_path %></div>
      <div class="breadcrumb-item">New Client</div>
    </div>
  </div>
  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>New Client</h4>
      </div>
      <div class="card-body">
        <%= render 'form', client: @client %>
      </div>
    </div>
  </div>
</section>

<%= link_to icon('fas fa-arrow-left', 'Back'), clients_path, class: 'btn btn-icon icon-left btn-secondary d-mobile-none' %>

<% content_for(:page_title, 'New Client') %>

app/views/clients/show.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Clients</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item"><%= link_to 'Clients', clients_path %></div>
      <div class="breadcrumb-item">Show Client</div>
    </div>
  </div>

  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>Show Client</h4>
      </div>
      <div class="card-body">
        <dl class="row">
        </dl>
      </div>
    </div>
  </div>
</section>

<%= link_to icon('fas fa-edit', 'Edit'), edit_client_path(@client), class: 'btn btn btn-icon icon-left btn-warning' %>
<%= link_to icon('fas fa-arrow-left', 'Back'), clients_path, class: 'btn btn-icon icon-left btn-secondary d-mobile-none' %>

<% content_for(:page_title, 'Show Client') %>