config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :attendees, controllers: { passwords: 'devise/attendees/passwords' }
  devise_for :users

  resources :events do
    post 'upload_attendees', on: :member
    post 'publish', on: :member
    post 'unpublish', on: :member
    resources :attendees
  end

  resources :contents
  resources :clients
  resources :tokens do
    post 'attach_content_hotspot', on: :collection
    post 'attach_url_hotspot', on: :collection
  end

  resources :hotspots, only: %i[create destroy]
  resources :labels do
    patch :update_text, on: :collection
  end

  root 'events#index'

  admin_web_constraint = lambda do |request|
    current_user = request.env['warden'].user(:user)
    current_user.present? && current_user.respond_to?(:has_role?) && current_user.has_role?(:superadmin)
  end

  constraints admin_web_constraint do
    mount Flipflop::Engine => '/flipflop'
  end
end

app/models/event.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: events
#
#  id                       :bigint           not null, primary key
#  end_time                 :datetime
#  invitation_scheduled     :boolean          default(FALSE)
#  invitation_sent          :boolean          default(FALSE)
#  landing_background_color :string
#  landing_foreground_color :string
#  landing_logo             :string
#  landing_prompt           :string
#  name                     :string
#  send_invitation_at       :datetime
#  slug                     :string
#  start_time               :datetime
#  timezone                 :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  client_id                :bigint           not null
#  main_entrance_id         :bigint
#
# Indexes
#
#  index_events_on_client_id         (client_id)
#  index_events_on_main_entrance_id  (main_entrance_id)
#
# Foreign Keys
#
#  fk_rails_...  (client_id => clients.id)
#  fk_rails_...  (main_entrance_id => rooms.id)
#
class Event < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :scoped, scope: :client

  acts_as_taggable_on :tags

  has_many :attendees, dependent: :destroy
  has_many :hotspots, dependent: :destroy
  has_many :labels, dependent: :destroy

  belongs_to :client
  belongs_to :main_entrance, class_name: 'Room'

  delegate :slug, to: :client, prefix: true, allow_nil: true
  delegate :path, to: :main_entrance, prefix: true, allow_nil: true
  delegate :name, to: :client, prefix: true, allow_nil: true

  validates :name,
            :start_time,
            :end_time,
            :landing_prompt,
            :landing_logo,
            :landing_background_color,
            :landing_foreground_color,
            :timezone, presence: true

  validates :timezone, inclusion: ActiveSupport::TimeZone.all.map(&:name)

  before_save :normalize_datetimes

  def key
    "#{client_slug}.#{slug}"
  end

  def configuration_key
    "event.#{key}"
  end

  def unpublish
    unpublish_event

    Attendee.unpublish(key)
    Hotspot.unpublish(key)
    Label.unpublish(key)
  end

  def publish
    publish_event

    # clean related models records before publish
    Attendee.unpublish(key)
    attendees.each(&:publish)

    Hotspot.unpublish(key)
    hotspots.each(&:publish)

    Label.unpublish(key)
    labels.each(&:publish)
  end

  def router_app_url
    "#{Config.event_url_root}/#{client_slug}/#{slug}"
  end

  def start_time_in_selected_zone
    dt_convert_to_zone(start_time, timezone)
  end

  def end_time_in_selected_zone
    dt_convert_to_zone(end_time, timezone)
  end

  private

  def normalize_datetimes
    self.start_time = dt_convert_to_app_zone(start_time)
    self.end_time = dt_convert_to_app_zone(end_time)
  end

  def dt_convert_to_zone(dt, timezone_name)
    tz = ActiveSupport::TimeZone[timezone_name]
    dt.in_time_zone(tz)
  end

  # converts the date in current app timezone
  def dt_convert_to_app_zone(dt)
    # create datetime instance in selected timezone
    dt_without_tz = dt.strftime('%Y-%m-%d %H:%M')
    dt_in_selected_timezone = dt_without_tz.in_time_zone(timezone)

    # app timezone
    app_tz = Time.zone

    dt_in_selected_timezone.in_time_zone(app_tz)
  end

  def unpublish_event
    Redis.current.del(configuration_key)
  end

  # rubocop:disable Metrics/AbcSize
  def publish_event
    Redis.current.hset(configuration_key, 'main_entrance', main_entrance_path)
    Redis.current.hset(configuration_key, 'start_time', time_to_publish_format(start_time))
    Redis.current.hset(configuration_key, 'end_time', time_to_publish_format(end_time))
    Redis.current.hset(configuration_key, 'landing_prompt', landing_prompt)
    Redis.current.hset(configuration_key, 'landing_logo', landing_logo)
    Redis.current.hset(configuration_key, 'landing_background_color', landing_background_color)
    Redis.current.hset(configuration_key, 'landing_foreground_color', landing_foreground_color)
  end
  # rubocop:enable Metrics/AbcSize

  def time_to_publish_format(time)
    (time.to_i * 1000).to_s
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy upload_attendees publish unpublish]
  before_action :set_dropdown_values, only: %i[new edit]
  after_action :clear_session, only: :edit

  def index
    @search = Event.includes(:client).reverse_chronologically.ransack(params[:q])
    authorize @search.result

    respond_to do |format|
      format.any(:html, :json) { @events = set_page_and_extract_portion_from @search.result }
      format.csv { render csv: @search.result }
    end
  end

  def show; end

  def new
    @event = Event.new
    authorize @event
  end

  def edit
    authorize @event

    setup_tab
    @attendees = set_page_and_extract_portion_from @event.attendees, ordered_by: { created_at: :desc }
    @navigation_tokens = Token.navigation
  end

  def create
    @event = Event.new(event_params)
    authorize @event

    if @event.save
      flash[:notice] = 'Event was successfully created.'
    else
      flash[:alert] = @event.errors.full_messages.to_sentence
    end

    respond_to do |format|
      format.html { redirect_to events_url }
    end
  end

  def update
    authorize @event

    if @event.update(event_params)
      flash[:notice] = 'Event was successfully updated.'
    else
      flash[:alert] = @event.errors.full_messages.to_sentence
    end

    respond_to do |format|
      format.html { redirect_to edit_event_url(@event) }
    end
  end

  def destroy
    authorize @event
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upload_attendees
    authorize @event
    importer = AttendeesImporter.new(@event, params[:upload][:file])

    if importer.call
      flash[:notice] = 'Attendees added'
    else
      flash[:error] = importer.errors_report
    end

    session[:attendees_report] = importer.logs_html_report
    redirect_to edit_event_url(@event, tab: 'attendees')
  end

  def publish
    @event.publish
    respond_to do |format|
      format.js { flash.now[:notice] = 'Event published' }
    end
  end

  def unpublish
    @event.unpublish
    respond_to do |format|
      format.js { flash.now[:notice] = 'Event unpublished' }
    end
  end

  private

  def set_event
    @event = Event.friendly.find(params[:id])
  end

  def set_dropdown_values
    @rooms = Room.all
    @clients = Client.order(:name)
    @content_images = Content.images.limit(5).order(:name)
  end

  def event_params
    params.require(:event).permit(
      :name, :start_time, :end_time, :client_id, :main_entrance_id, :tag_list,
      :landing_prompt, :landing_logo, :landing_background_color, :landing_foreground_color,
      :invitation_scheduled, :send_invitation_at, :timezone
    )
  end

  def setup_tab
    tab = params[:tab].to_s.downcase
    @tab = %w[attendees permissions rooms].include?(tab) ? tab : 'details'
  end

  def clear_session
    session[:attendees_report] = nil if session[:attendees_report].present?
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/events/_add_content_modal_form.html.erb
<div class="modal fade" id="bindContentModal" tabindex="-1" aria-labelledby="bindContentModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="bindContentModalLabel">
          Set content to
          <code id='token-title-modal'></code>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for(:content_hotspot, url: attach_content_tokens_path) do |form| %>
        <div class="modal-body">
          <%= form.hidden_field :token_id, class: 'form-control' %>
          <%= form.hidden_field :event_id, class: 'form-control', value: event.id %>

          <div class="row">
            <div class="col-6 form-group">
              <%= form.label :text, 'Label' %>
              <%= form.text_field :text, class: 'form-control' %>
            </div>

            <div class="col-6 form-group">
              <%= form.label :content_id, 'Content' %>
              <%= form.collection_select :content_id, Content.all, :id, :name, {}, class: 'form-control', data: { controller: 'select' } %>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= form.submit 'Add content', class: "btn btn-primary" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/events/_attendees.html.erb
<div class="row">
  <div class="col-9">
    <div class="card card-highlight-info">
      <div class="card-body">
        <%= form_for ([event, Attendee.new]) do |f| %>
          <div class="row">
            <div class="col-6 col-lg-4">
              <div class="form-group">
                <%= f.text_field :name, placeholder: 'Name', class: 'form-control' %>
              </div>
            </div>
            <div class="col-6 col-lg-4">
              <div class="form-group">
                <%= f.text_field :email, placeholder: 'Email', class: 'form-control' %>
              </div>
            </div>
            <div class="col-6 col-lg-4">
              <div class="form-group">
                <%= f.text_field :password, placeholder: 'Password', class: 'form-control' %>
              </div>
            </div>
          </div>
          <div class="float-right">
            <%= f.submit 'ADD', class: 'btn btn-info', style: 'width: 120px;' %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="card card-highlight-info" data-controller="infinite-page">
      <div class="table-responsive">
        <table class="table table-striped table-md">
          <tbody data-target="infinite-page.container" >
            <% @attendees.each do |a| %>
              <tr data-target="infinite-page.item">
                <td><%= a.email %></td>
                <td><%= a.name %></td>
                <td>
                  <%= link_to icon('fas fa-trash'), event_attendee_path(event, a), title: 'Destroy it', class: 'btn btn-icon btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?', remote: false } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% if @page %>
          <%= link_to 'Next page', edit_event_path(event, page: @page.next_number), data: { target: 'infinite-page.more' } unless @page.last? %>
        <% end %>
      </div>
    </div>

    <%= simple_form_for(:upload, url: upload_attendees_event_path(id: event.id)) do |f| %>
      <div class="row">
        <div class="col-4">
          <div class="custom-file">
            <%= f.file_field :file, label: 'Report', class: 'custom-file-input form-control-md', id: 'upload-attendees-select', accept: '.csv' %>
            <%= f.label :file, 'Choose file', class: 'custom-file-label', id:  'upload-attendees-label' %>
          </div>
        </div>
        <button id='upload-attendees-btn' class='btn btn-light' disabled='true' title='Upload'>
          <i class="fas fa-upload"></i>
        </button>
      </div>
    <% end %>

    <% if session[:attendees_report].present? %>
      <div class="mt-5">
        <h3>Operation logs</h3>
        <div class="p-4">
          <%= session[:attendees_report].html_safe %>
        </div>
      </div>
    <% end %>

    <% if Flipflop.registration? %>
      <div class="card card-highlight-info mt-4">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item active" style="font-size: 1.3em;">
              <%= pretty_time(event.start_time) %>
            </li>
          </ol>
        </nav>

        <%= form_with(model: event, data: { controller: 'validation' }) do |form| %>
          <div class="row">
            <div class="col-6">
              <div class="form-group">
                <%= form.label :send_invitation_at %>
                <%= form.text_field :send_invitation_at, placeholder: 'Name', class: 'form-control datetimepicker' %>
              </div>
            </div>

            <div class="col-6">
              <div class="form-group">
                <%= label_tag :template, 'Invitation Email Template (TBD)' %>
                <%= text_field_tag :template, nil, placeholder: 'Template TBD', class: 'form-control' %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-3">
              <div class="form-group">
                <label for="scheduled">Send emails with an invitation out</label>
                <%= form.check_box :invitation_scheduled, style: 'height: 20px; width: 25px;', class: 'form-control' %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-12">
              <div class="float-right">
                <%= form.submit 'Update', class: 'btn btn-info', style: 'width: 120px;' %>
              </div>
            </div>
          </div>

        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_hotspot_create.html.erb
<tr>
  <td><%= token.name %></td>
  <td><%= token.description %></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td>
      <button type="button" class="btn btn-primary btn-sm bind-content-to-token-btn" data-toggle="modal" data-target="#bindContentModal" data-token-id='<%= token.id %>' data-token-title='<%= "#{room.name} - #{token.name}".truncate(45) %>'>
        Set content
      </button>
      <button type="button" class="btn btn-info btn-sm bind-url-to-token-btn" data-toggle="modal" data-target="#bindUrlModal" data-token-id='<%= token.id %>' data-token-title='<%= "#{room.name} - #{token.name}".truncate(45) %>'>
        Set URL
      </button>
  </td>
</tr>

app/views/events/_hotspot_details.html.erb
<tr>
  <td><%= token.name %></td>
  <td><%= token.description %></td>
  <td>
    <%= link_to '#', class: 'edit-label-link', data: { toggle: 'modal', target: '#editLabelModal', label: hotspot&.label&.text, id: hotspot&.label&.id } do %>
      <%= hotspot&.label&.text %>
      <span class='fas fa-edit'></span>
    <% end %>
  </td>

  <% if hotspot&.display? && hotspot&.content %>
    <td>File</td>
    <td>
      <%= hotspot&.content&.file&.filename %>
      <%= link_to edit_content_path(hotspot.content), target: '_blank' do %>
        <i class='fas fa-edit'></i>
      <% end %>

    </td>
    <td>
      <% hotspot&.content&.tags&.each do |tag| %>
        <span class="badge badge-light"><%= tag %></span>
      <% end %>
    </td>
  <% else %>
    <td><%= hotspot&.type&.humanize %></td>
    <td>
      <%= link_to hotspot.destination_url, hotspot.destination_url, target: '_blank' %>
    </td>
    <td></td>
  <% end %>

  <td>
    <%= link_to icon('fas fa-trash'), hotspot_path(hotspot), title: 'Unset hotspot', class: 'btn btn-icon btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?', remote: true } %>
  </td>
</tr>

app/views/events/_hotspots.html.erb
<div class="table-responsive">
  <table class="table table-striped table-md">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Label</th>
        <th>Type</th>
        <th>Content</th>
        <th>Tags</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% tokens.each do |token| %>
        <% hotspot = token.hotspot(event_id: event.id) %>
        <% if hotspot.nil? %>
          <%= render 'hotspot_create', token: token, room: room %>
        <% else %>
          <%= render 'hotspot_details', hotspot: hotspot, token: token, room: room %>
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/_tokens_table.html.erb
<div class="table-responsive">
  <table class="table table-striped table-md">
    <thead>
      <tr>
        <th>Name</th>
        <th>Token</th>
        <th>Label</th>
        <% if type == :hotspots %>
          <th>Type</th>
          <th>Content</th>
          <th>Tags</th>
        <% end %>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% tokens.each do |token| %>
        <tr>
          <td><%= token.name %></td>
          <td><%= token.token %></td>
          <td>
            <% if (label = token.label(event_id: event.id)) %>
              <%= link_to '#', class: 'edit-label-link', data: { toggle: 'modal', target: '#editLabelModal', label: label.text, id: label.id } do %>
                <%= label.text %>
                <span class='fas fa-edit'></span>
              <% end %>
            <% end %>
          </td>

          <% hotspot = token.hotspot(event_id: event.id) %>
          <% if type == :hotspots %>
            <% if hotspot&.display? && hotspot&.content %>
              <td>File</td>
              <td>
                <%= hotspot&.content&.file&.filename %>
                <%= link_to edit_content_path(hotspot.content), target: '_blank' do %>
                  <i class='fas fa-edit'></i>
                <% end %>

              </td>
              <td>
                <% hotspot&.content&.tags&.each do |tag| %>
                  <span class="badge badge-light"><%= tag %></span>
                <% end %>
              </td>
            <% elsif hotspot %>
              <td><%= hotspot&.type&.humanize %></td>
              <td>
                <%= link_to hotspot.destination_url, hotspot.destination_url, target: '_blank' %>
              </td>
              <td></td>
            <% else %>
              <td></td>
              <td></td>
              <td></td>
            <% end %>

          <% end %>
          <td>
            <% if type == :hotspots && hotspot.nil? %>
              <button type="button" class="btn btn-primary btn-sm bind-content-to-token-btn" data-toggle="modal" data-target="#bindContentModal" data-token-id='<%= token.id %>' data-token-title='<%= "#{room.name} - #{token.name}".truncate(45) %>'>
                Set content
              </button>

              <button type="button" class="btn btn-info btn-sm bind-url-to-token-btn" data-toggle="modal" data-target="#bindUrlModal" data-token-id='<%= token.id %>' data-token-title='<%= "#{room.name} - #{token.name}".truncate(45) %>'>
                Set URL
              </button>
            <% end %>

            <%= link_to icon('fas fa-trash'), hotspot_path(hotspot), title: 'Unset hotspot', class: 'btn btn-icon btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?', remote: true } if hotspot %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/edit.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>
      <%= @event.name %>
    </h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item"><%= link_to 'Events', events_path %></div>
      <div class="breadcrumb-item">Show Event</div>
    </div>
  </div>

  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>Event Parameters</h4>
        <div class="card-header-action">
          <%= link_to icon('fas fa-database', 'Publish'), publish_event_path(id: @event.id), class: 'btn btn-icon icon-left btn-primary', method: :post, remote: true %>
          <%= link_to icon('fas fa-unlink', 'Unpublish'), unpublish_event_path(id: @event.id), class: 'btn btn-icon icon-left btn-primary', method: :post, remote: true %>

          <%= link_to icon('fas fa-external-link-alt', 'Open Event'), @event.router_app_url, class: 'btn btn-icon icon-left btn-primary', target: '_blank' %>
        </div>
      </div>
      <div class="card-body">
        <ul class="nav nav-tabs" id="myTab2" role="tablist">
          <li class="nav-item">
            <% selected = (@tab == 'details') %>
            <%= link_to 'Details', '#home2', id: 'home-tab2', data: { toggle: 'tab' }, role: 'tab', aria: { controls: 'home', selected: selected }, class: "nav-link #{'active' if selected}" %>
          </li>
          <li class="nav-item">
            <% selected = (@tab == 'attendees') %>
            <%= link_to 'Attendees', '#profile2', id: 'profile-tab2', data: { toggle: 'tab' }, role: 'tab', aria: { controls: 'profile', selected: selected }, class: "nav-link #{'active' if selected}" %>
          </li>
          <li class="nav-item">
            <% selected = (@tab == 'permissions') %>
            <%= link_to 'Permissions', '#permissions', id: 'contact-tab2', data: { toggle: 'tab' }, role: 'tab', aria: { controls: 'contact', selected: selected }, class: "nav-link #{'active' if selected}" %>
          </li>
          <li class="nav-item">
            <% selected = (@tab == 'rooms') %>
            <%= link_to 'Rooms', '#rooms', id: 'contact-tab2', data: { toggle: 'tab' }, role: 'tab', aria: { controls: 'contact', selected: selected }, class: "nav-link #{'active' if selected}" %>
          </li>
        </ul>
        <div class="tab-content tab-bordered" id="myTab3Content">
          <div class="tab-pane fade <%= "show active" if @tab == 'details' %>" id="home2" role="tabpanel" aria-labelledby="home-tab2">
            <%= render 'form', event: @event %>
          </div>
          <div class="tab-pane fade <%= "show active" if @tab == 'attendees' %>" id="profile2" role="tabpanel" aria-labelledby="profile-tab2">
            <%= render 'attendees', event: @event %>
          </div>
          <div class="tab-pane fade <%= "show active" if @tab == 'permissions' %>" id="permissions" role="tabpanel" aria-labelledby="contact-tab2">
            TBD
          </div>
          <div class="tab-pane fade <%= "show active" if @tab == 'rooms' %>" id="rooms" role="tabpanel" aria-labelledby="contact-tab2">
            <%= render 'rooms', rooms: @rooms, event: @event %>
            <%= render 'navigations', tokens: @navigation_tokens, event: @event %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<%= link_to icon('fas fa-arrow-left', 'Back'), events_path, class: 'btn btn-icon icon-left btn-secondary d-mobile-none' %>

<%= render 'events/modals/add_content_modal_form', event: @event %>
<%= render 'events/modals/set_url_modal_form', event: @event %>
<%= render 'events/modals/edit_label_modal_form' %>

<% content_for(:page_title, 'Show Event') %>

app/views/events/index.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Events</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item">List of Events</div>
    </div>
  </div>

  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>List of Events</h4>
        <div class="card-header-action">
          <%= link_to icon('fas fa-plus', 'New Event'), new_event_path, class: 'btn btn-icon icon-left btn-primary' %>
          <%= render 'shared/card_dropdown' do %>
            <%= link_to icon('fas fa-download', 'Export Data'), events_path(format: :csv, q: request.params[:q]), class: 'dropdown-item has-icon' %>
            <%= link_to icon('fas fa-print', 'Print Page'), 'javascript:window.print()', class: 'dropdown-item has-icon' %>
          <% end %>
        </div>
      </div>
      <div class="card-body" data-controller="infinite-page">
        <%= search_form_for @search, remote: true, data: { controller: 'turbolinks-form' }, html: { class: 'form-row' } do |f| %>
          <div class="form-group col-sm-10">
            <%= f.text_field :name_cont, class: 'form-control m-input m-input--solid', placeholder: 'Name' %>
          </div>
          <div class="form-group col-sm-2 text-right">
            <%= f.button icon('fas fa-search', 'Search'), name: nil, class: 'btn btn-icon icon-left btn-primary' %>
          </div>
        <% end %>
        <div class="table-responsive">
          <table class="table table-striped table-md">
            <thead>
              <tr>
                <th><%= sort_link_turbo(@search, :name, 'Event Name') %></th>
                <th>Client</th>
                <th>Tags</th>
                <th><%= sort_link_turbo(@search, :start_time, 'Start') %></th>
                <th><%= sort_link_turbo(@search, :end_time, 'End') %></th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody data-target="infinite-page.container">
              <% @events.each do |event| %>
                <tr data-target="infinite-page.item">
                  <td>
                    <%= link_to event.name, edit_event_path(event) %>
                  </td>
                  <td><%= event.client_name %></td>
                  <td>
                    <% event.tags.each do |tag| %>
                      <span class='badge badge-light'><%= tag %></span>
                    <% end %>
                  </td>
                  <td><%= pretty_event_time(event.start_time_in_selected_zone) %></td>
                  <td><%= pretty_event_time(event.end_time_in_selected_zone) %></td>
                  <td>
                    <%= link_to icon('fas fa-database'), publish_event_path(event), title: 'Publish', method: :post, remote: true, class: 'btn btn-icon btn-sm btn-primary mr-1' %>
                    <%= link_to icon('fas fa-unlink'), unpublish_event_path(event), title: 'Unpublish', method: :post, remote: true, class: 'btn btn-icon btn-sm btn-primary mr-1' %>
                    <%= link_to icon('fas fa-edit'), edit_event_path(event), title: 'Edit it', class: 'btn btn-icon btn-sm btn-warning mr-1' %>
                    <%= link_to icon('fas fa-trash'), event, title: 'Destroy it', class: 'btn btn-icon btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?', remote: true } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= link_to 'Next page', events_path(page: @page.next_number, q: request.params[:q]), data: { target: 'infinite-page.more' } unless @page.last? %>
        </div>
      </div>
    </div>
  </div>
</section>

<% content_for(:page_title, 'List of Events') %>

app/views/events/new.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Events</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item"><%= link_to 'Events', events_path %></div>
      <div class="breadcrumb-item">New Event</div>
    </div>
  </div>
  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>New Event</h4>
      </div>
      <div class="card-body">
        <%= render 'form', event: @event %>
      </div>
    </div>
  </div>
</section>

<%= link_to icon('fas fa-arrow-left', 'Back'), events_path, class: 'btn btn-icon icon-left btn-secondary d-mobile-none' %>

<% content_for(:page_title, 'New Event') %>

app/views/events/publish.js.erb
$('#toastr-alerts').html("<%= j(render 'shared/toastr') %>");

app/views/events/unpublish.js.erb
$('#toastr-alerts').html("<%= j(render 'shared/toastr') %>");